wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.46.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731336845
    t:
      1:
      - 1
      - 5
      - 11
      - 30
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 14
      - 23
      4: 3.12.0
      5: 0.17.9
      6: 4.46.2
      8:
      - 5
      13: linux-x86_64
